[config]
# Size of spectra to be tested
spectra_size = 2

# Approximate number of spectra mutations to occur
spectra_mutations = 100

# From the starting spectra how many mutations should be applied before minimization starts.
mutated_spectra_to_evaluate = 1

# TODO: This would benifit from being an enum or something easier to understand
# The mode of operation. See documentation.
mode = 2

# The starting spectra to test. This changes based on mode.
starting_spectra = [1,0,0]