[config]
# Size of matrices to be testing
spectra_size = 2

# Approximate number of matrices to be validating the polynomial at.
spectra_mutations = 8000

# From the starting polynomial how many mutations should be applied before minimization starts.
mutated_spectra_to_evaluate = 1

# TODO: This would benifit from being an enum or something easier to understand
# The mode of operation. See documentation.
mode = 1

# The starting polynomial to test. This changes based on mode.
starting_spectra = [1,-1.2]